version: "3"
services:
 wireguard:
    container_name: wg-manager
    image: perara/wg-manager
    cap_add:
      - NET_ADMIN
    #network_mode: host # Alternatively
    ports:
       - 51800:51900/udp
       - 8888:8888
    volumes:
      - ./wg-manager:/config
    environment:
      HOST: 0.0.0.0
      PORT: 8888
      ADMIN_PASSWORD: admin
      ADMIN_USERNAME: admin
      WEB_CONCURRENCY: 1
